version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend      

  backend:
    build: ./backend
    expose:
      - "5000"        
    depends_on:
      - database