version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Mappt Port 3000 des Containers auf Port 3000 des Hosts
    depends_on:
      - backend      # Stellt sicher, dass das Backend vor dem Frontend gestartet wird

  backend:
    build: ./backend
    expose:
      - "5000"        # Exponiert den Port 5000 für das interne Netzwerk (nicht nach außen)
    depends_on:
      - database